[
  {
    category: "living",
    product: "hi",
    img1: "https://hatil.com/sites/default/files/Durjan-266%20.jpg",
    img2: "https://hatil.com/sites/default/files/Durjan-266.jpg",
    img3: "https://hatil.com/sites/default/files/product_set_images/638117164611897307_0%20-Durjan-266-HTL-201-266-10-2_8.jpg",
    description:
      "Made from Kiln-dried imported Beech wood and veneered engineered wood.High quality environment friendly Italian Ultra Violet (UV) and Polyurethane (PU) Lacquer in antique finish.Imported fabric upholstery with soft and durable cushioning. Fabric can be selected from available options.Fabric can dry-cleaned.Indoor use only.Weight single seater 16.",
    name: "Sofa Durian-266",
    quality: "Best",
    quantity: "5",
    price: "40000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SX266",
  },

  {
    category: "bedroom",
    "": "",
    img1: "https://hatil.com/sites/default/files/Obsession-151%20.jpg",
    img2: "https://hatil.com/sites/default/files/Obsession-151%20Bed%20HATIL%20%20modern%20bedroom%20online%20buy%20Bangladesh%20low%20price.jpg",
    img3: "https://hatil.com/sites/default/files/product_set_images/637785368417694257_2.1.jpg",
    description:
      "Made from Kiln-dried imported Beech wood, veneered engineered wood and veneered MDF.High quality environment friendly Italian Ultra Violet (UV) Lacquer in antique finish.Any assembly or installation required will be done by the team at the time of delivery (one day after delivery for CKD items)",
    name: "Bed Obsession-151",
    quality: "Best",
    quantity: "5",
    price: "50000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SX151",
  },
  {
    category: "dining",
    "": "",
    img1: "https://hatil.com/sites/default/files/Fairbanks-109%20and%20Carp-109%20_0.jpg",
    img2: "https://hatil.com/sites/default/files/Fairbanks-109%20and%20Carp-109_0.jpg",
    img3: "https://hatil.com/sites/default/files/product_set_images/Fairbanks-109-and-Carp-109-4-Chair_637826376960620236_Fairbanks-109%20and%20Carp-109%20-dinning%20set-1.jpg",
    description:
      "Made from Kiln-dried imported Beech wood and veneered engineered wood.High quality environment friendly Italian Ultra Violet (UV) and Polyurethane (PU) Lacquer in antique finish.Imported high quality hardware fittings.",
    name: "Dining Fairbanks-109",
    quality: "Best",
    quantity: "5",
    price: "10000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SX109",
  },
  {
    category: "kids",
    "": "",
    img1: "https://hatil.com/sites/default/files/Canberra-101-t.jpg",
    img2: "https://hatil.com/sites/default/files/Canberra-101.jpg",
    img3: "https://hatil.com/sites/default/files/product_set_images/637955677735038130_1.jpg",
    description:
      "Made from superior quality melamine faced particle board with international standard density and load bearing capacity.Same color edge banding done in latest Homag line.Any assembly or installation required will be done by the team at the time of delivery (one day after delivery for CKD items).Imported high quality hardware fittings.Indoor use only ",
    name: "Reading Table Canberra-101",
    quality: "Best",
    quantity: "5",
    price: "13000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SX",
  },
  {
    category: "institute",
    "": "",
    img1: "https://hatil.com/sites/default/files/Virgo-103%20.jpg",
    img2: "https://hatil.com/sites/default/files/Virgo-103.jpg",
    img3: "https://hatil.com/sites/default/files/product_set_images/638041903178914023_0%20-Virgo-103-HIF-267-103-10-1-88_15.jpg",
    description:
      "Made from Kiln-dried imported Beech wood and veneered engineered wood.High quality environment friendly Italian Ultra Violet (UV) and Polyurethane (PU) Lacquer in antique finish.Imported fabric upholstery with soft and durable cushioning. Fabric can be selected from available options.Fabric can dry-cleaned.Indoor use only.Weight single seater 16.",
    name: " Bar Stool Virgo-103",
    quality: "Best",
    quantity: "5",
    price: "10000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SX103",
  },
  {
    category: "door",
    "": "",
    img1: "https://hatil.com/sites/default/files/HCL-102-176-BCH-1-66_0.png",
    img2: "https://hatil.com/sites/default/files/HCL-102-179-OAK-1-88_0.png",
    img3: "https://hatil.com/sites/default/files/HCL-102-182-OAK-1-88_0.png",
    description:
      "Made from Kiln-dried imported Beech wood and veneered engineered wood.High quality environment friendly Italian Ultra Violet (UV) and Polyurethane (PU) Lacquer in antique finish.Imported fabric upholstery with soft and durable cushioning. Fabric can be selected from available options.Fabric can dry-cleaned.Indoor use only.Weight single seater 16.",
    name: "Solid Engineered Wooden Door",
    quality: "Best",
    quantity: "5",
    price: "12000",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SXWD",
  },
  {
    category: "interior",
    "": "",
    img1: "https://hatil.com/sites/default/files/hatil-com_interior_office-01.png",
    img2: "https://hatil.com/sites/default/files/hatil-com_interior_office-02.png",
    img3: "https://hatil.com/sites/default/files/hatil-com_interior_office-03.png",
    description:
      "Made from Kiln-dried imported Beech wood and veneered engineered wood.High quality environment friendly Italian Ultra Violet (UV) and Polyurethane (PU) Lacquer in antique finish.Imported fabric upholstery with soft and durable cushioning. Fabric can be selected from available options.Fabric can dry-cleaned.Indoor use only.Weight single seater 16.",
    name: "Interior Design",
    quality: "",
    quantity: 0,
    price: "0",
    advertised: "no",
    sold: "339",
    recommended: "yes",
    rating: "5",
    pid: "SXI",
  },
];
